#!/usr/bin/env bash
# Generates per-install secrets into .context/secrets.env (git-ignored) on first run.
# Nothing secret is committed: the config files in tyk/ only carry placeholders, and
# docker-compose.yml passes these values to the components as environment variables.
# ./down.sh deletes .context/, so a fresh install gets fresh secrets.
set -euo pipefail
cd "$(dirname "$0")/.."

FILE=.context/secrets.env
[[ -s "$FILE" ]] && exit 0
mkdir -p .context

hex() { openssl rand -hex "$1"; }
pw()  { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"; }

umask 077
cat > "$FILE" <<EOF
# Generated by scripts/init-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
# Gateway API secret (x-tyk-authorization) - shared by all gateways, the Dashboard and MDCB
TYK_GATEWAY_SECRET=$(hex 16)
# Gateway <-> Dashboard node registration secret
TYK_NODE_SECRET=$(hex 16)
# Dashboard Admin API secret (admin-auth header)
TYK_ADMIN_SECRET=$(hex 16)
# MDCB secure HTTP endpoints (/dataplanes) secret (X-Tyk-Authorization)
TYK_MDCB_SECRET=$(hex 16)
# Dashboard login passwords
TYK_ADMIN_PASSWORD=$(pw 16)
TYK_MDCB_USER_PASSWORD=$(pw 16)
# OpenTelemetry Demo feature-flag UI (Phoenix) session key
FLAGD_UI_SECRET_KEY_BASE=$(hex 32)
EOF
echo "Secrets: generated $FILE"
